/**
 * /api/blog-agent — the JOSHRIX Content Agent: SEO blog on autopilot.
 *   GET  ?public=1            → published post index (public, for /blog + admin)
 *   GET  (cron / admin key)   → autopilot: pick the next editorial topic, write
 *                               with Claude, publish. Wired to Vercel Cron.
 *   POST { topic? }           → admin: write & publish a post now (custom topic)
 * Auth for generation: x-admin-key === MODERATION_KEY, or the Vercel Cron
 * Authorization: Bearer CRON_SECRET header. Fail closed otherwise.
 * Every post ships with meta description, keywords, internal links to live
 * pages/games (dynamic linking), and ready-to-paste social captions.
 */
import Anthropic from "@anthropic-ai/sdk";
import { getDb, ensureBlogSchema, ensureGameSchema, saveBlogPost, getBlogPost, listBlogPosts, countBlogPosts, listApprovedGames } from "./_ledger";

const SITE = "https://www.joshrix.com";

/** Rotating editorial calendar — high-intent queries for the AI game-creation market. */
export const EDITORIAL_TOPICS = [
  "How to create your own video game with AI — no coding required",
  "Can you really make money selling AI-created games? The honest economics",
  "AI game generator vs hiring a game studio: cost, speed and ownership compared",
  "From idea to playable game in one afternoon: a step-by-step walkthrough",
  "The 7 game concepts that work best with AI game creation tools",
  "How game creators keep 100% ownership of their IP on AI platforms",
  "Publishing your game to the App Store and Google Play without a developer account",
  "What makes a browser game go viral: share links, remixing and play loops",
  "Creating games in any language: why multilingual game creation matters",
  "Kid-safe game design: building magical worlds for young players responsibly",
  "The remix economy: how forking games earns royalties for original creators",
  "Free AI tools are lying to you: why paid AI compute makes better games",
  "How human moderation keeps an AI game platform safe and store-compliant",
  "Progressive Web Apps: why the install-free game is winning on mobile",
];

const CONTENT_SYSTEM = `You are the JOSHRIX Content Agent — an expert SEO writer for joshrix.com, the AI game-creation platform (tagline: "Create Worlds. Build Games. Own the Future."). Creators describe a game in any language, pay for AI work in ACUs, and the platform's agents forge a real playable browser game which goes public after human moderation, on its own share link and in the JOSHRIX Arcade.
Write ONE complete blog article for the given topic. Respond with ONLY a JSON object (no markdown fences) with exactly these keys:
title (string, <=60 chars, primary keyword near the front),
slug (kebab-case, <=60 chars, no stopwords),
metaDescription (string, <=155 chars, compelling, includes the primary keyword),
keywords (string[] of 6-10 search phrases),
excerpt (string, 1-2 sentences),
html (string: the article BODY as an HTML fragment — no <html>/<head>/<body>. ~1100-1400 words. Structure: hook intro <p>, then 4-6 <h2> sections with <p>/<ul> content, one comparison or checklist <ul>, a <h2>FAQ</h2> with three <h3> questions each followed by a <p> answer, and a closing call-to-action paragraph. Naturally weave in 3-6 internal links from the provided link list using descriptive anchor text. Confident, concrete, zero fluff; no fabricated statistics, no competitor names.),
socialX (string <=260 chars for X/Twitter with 2-3 hashtags),
socialLinkedIn (string, 400-600 chars, professional angle),
socialFacebook (string, 200-400 chars, community angle),
hashtags (string[] of 5-8 without #).
Write in English unless the topic is clearly in another language.`;

function slugify(s: string): string {
  return s.normalize("NFKD").replace(/[̀-ͯ]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60) || "post";
}

function demoArticle(topic: string) {
  const t = topic.slice(0, 55);
  return {
    title: t, slug: slugify(topic), metaDescription: `${t} — a practical guide from the JOSHRIX team.`.slice(0, 155),
    keywords: ["ai game creation", "make a game with ai", "joshrix"], excerpt: `A practical look at: ${topic}.`,
    html: `<p>${topic} — this article was generated by the offline demo agent. With AI keys configured, the Content Agent writes a full SEO article here.</p><h2>Start forging</h2><p>Describe your world in the <a href="${SITE}/studio.html">JOSHRIX Studio</a>, play finished games in the <a href="${SITE}/arcade.html">Arcade</a>, and see plans on the <a href="${SITE}/pricing.html">pricing page</a>.</p>`,
    socialX: `${t} — new on the JOSHRIX blog. #gamedev #AI`, socialLinkedIn: `New on the JOSHRIX blog: ${topic}.`, socialFacebook: `New post: ${topic}`, hashtags: ["gamedev", "ai", "joshrix"],
  };
}

async function generateArticle(topic: string, liveGames: Array<{ id: string; title: string }>) {
  if (!process.env.ANTHROPIC_API_KEY) return { article: demoArticle(topic), provider: "demo" as const };
  const anthropic = new Anthropic();
  const links = [
    `${SITE}/studio.html — the Studio (create a game)`,
    `${SITE}/arcade.html — the Arcade (play free games)`,
    `${SITE}/pricing.html — plans, ACU packs and store distribution pricing`,
    `${SITE}/how-it-works.html — how the agent fleet forges games`,
    ...liveGames.slice(0, 3).map((g) => `${SITE}/play/${g.id} — live player-made game "${g.title}"`),
  ];
  const msg = await anthropic.messages.create({
    model: "claude-sonnet-5",
    max_tokens: 6000,
    system: CONTENT_SYSTEM,
    messages: [{ role: "user", content: `Topic: ${topic}\n\nInternal links available (use 3-6, exact URLs):\n${links.join("\n")}` }],
  });
  const text = msg.content.filter((b): b is Anthropic.TextBlock => b.type === "text").map((b) => b.text).join("");
  const start = text.indexOf("{"); const end = text.lastIndexOf("}");
  if (start === -1 || end === -1) throw new Error("Content Agent returned no JSON article");
  const a = JSON.parse(text.slice(start, end + 1));
  if (!a.title || !a.html || !a.metaDescription) throw new Error("Content Agent article missing required fields");
  a.slug = slugify(a.slug || a.title);
  return { article: a, provider: "claude" as const };
}

function authorised(req: any): boolean {
  const key = process.env.MODERATION_KEY;
  if (key && req.headers?.["x-admin-key"] === key) return true;
  const cron = process.env.CRON_SECRET;
  if (cron && req.headers?.["authorization"] === `Bearer ${cron}`) return true;
  return false;
}

export default async function handler(req: any, res: any) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, x-admin-key");
  if (req.method === "OPTIONS") return res.status(204).end();

  const sql = getDb();

  // public post index — powers /blog and the admin list
  if (req.method === "GET" && String(req.query?.public ?? "") === "1") {
    if (!sql) return res.status(200).json({ posts: [], mode: "no_db" });
    await ensureBlogSchema(sql);
    const posts = (await listBlogPosts(sql)).map((p) => ({
      slug: p.slug, title: p.title, description: p.description, excerpt: p.excerpt, createdAt: p.created_at, url: `/blog/${p.slug}`,
    }));
    return res.status(200).json({ posts, count: posts.length });
  }

  // generation — cron (GET) or admin (GET/POST with optional custom topic)
  if (!authorised(req)) return res.status(401).json({ error: "Admin key or cron secret required" });
  if (!sql) return res.status(503).json({ error: "DATABASE_URL missing — blog needs the database.", mode: "no_db" });

  try {
    await ensureBlogSchema(sql);
    await ensureGameSchema(sql);
    const customTopic = req.method === "POST" ? String((req.body ?? {}).topic ?? "").trim() : "";
    const n = await countBlogPosts(sql);
    const topic = customTopic || EDITORIAL_TOPICS[n % EDITORIAL_TOPICS.length];
    const liveGames = (await listApprovedGames(sql, 3)) as Array<{ id: string; title: string }>;
    const { article, provider } = await generateArticle(topic, liveGames);

    // never overwrite an existing slug — suffix when the calendar wraps around
    let slug = article.slug;
    if (await getBlogPost(sql, slug)) slug = `${slug}-${n + 1}`;
    await saveBlogPost(sql, {
      slug, title: article.title, description: article.metaDescription,
      keywords: (article.keywords || []).join(", "), excerpt: article.excerpt ?? null, html: article.html,
      social: { x: article.socialX, linkedin: article.socialLinkedIn, facebook: article.socialFacebook, hashtags: article.hashtags },
      topic, provider,
    });
    return res.status(200).json({ ok: true, slug, url: `/blog/${slug}`, title: article.title, provider, topic });
  } catch (err: any) {
    return res.status(502).json({ error: "Content Agent failed", detail: String(err?.message ?? err) });
  }
}
